I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 47, in script
    $ pc.equip_familiar(pixie)
  File "game/script.rpy", line 47, in <module>
    $ pc.equip_familiar(pixie)
  File "game/character.rpy", line 28, in equip_familiar
    self.unequip_familiar(self, familiar)
TypeError: unequip_familiar() takes exactly 1 argument (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 47, in script
    $ pc.equip_familiar(pixie)
  File "E:\Applications\renpy-7.1.1-sdk\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\Applications\renpy-7.1.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 47, in <module>
    $ pc.equip_familiar(pixie)
  File "game/character.rpy", line 28, in equip_familiar
    self.unequip_familiar(self, familiar)
TypeError: unequip_familiar() takes exactly 1 argument (3 given)

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Thalassa 1.0
Sun Nov 11 11:25:14 2018
